package br.com.guilherme_momolli.controle_patrimonial.model.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum Pais {

    AFEGANISTAO("Afeganistão"),
    AFRICA_DO_SUL("África do Sul"),
    ALBANIA("Albânia"),
    ALEMANHA("Alemanha"),
    ANDORRA("Andorra"),
    ANGOLA("Angola"),
    ANGUILLA("Anguilla"),
    ANTARTIDA("Antártida"),
    ANTIGUA_E_BARBUDA("Antígua e Barbuda"),
    ARABIA_SAUDITA("Arábia Saudita"),
    ARGELIA("Argélia"),
    ARGENTINA("Argentina"),
    ARMENIA("Armênia"),
    ARUBA("Aruba"),
    AUSTRALIA("Austrália"),
    AUSTRIA("Áustria"),
    AZERBAIJAO("Azerbaijão"),
    BAHAMAS("Bahamas"),
    BAHREIN("Bahrein"),
    BANGLADESH("Bangladesh"),
    BARBADOS("Barbados"),
    BELARUS("Belarus"),
    BELGICA("Bélgica"),
    BELIZE("Belize"),
    BENIN("Benin"),
    BERMUDA("Bermuda"),
    BOLIVIA("Bolívia"),
    BOSNIA_E_HERZEGOVINA("Bósnia e Herzegovina"),
    BOTSWANA("Botswana"),
    BRASIL("Brasil"),
    BRUNEI("Brunei"),
    BULGARIA("Bulgária"),
    BURKINA_FASO("Burkina Faso"),
    BURUNDI("Burundi"),
    BUTAO("Butão"),
    CABO_VERDE("Cabo Verde"),
    CAMAROES("Camarões"),
    CAMBOJA("Camboja"),
    CANADA("Canadá"),
    CATAR("Catar"),
    CAZAQUISTAO("Cazaquistão"),
    CHADE("Chade"),
    CHILE("Chile"),
    CHINA("China"),
    CHIPRE("Chipre"),
    COLOMBIA("Colômbia"),
    COMORES("Comores"),
    CONGO("Congo"),
    COREIA_DO_NORTE("Coreia do Norte"),
    COREIA_DO_SUL("Coreia do Sul"),
    COSTA_DO_MARFIM("Costa do Marfim"),
    COSTA_RICA("Costa Rica"),
    CROACIA("Croácia"),
    CUBA("Cuba"),
    CURACAO("Curaçao"),
    DINAMARCA("Dinamarca"),
    DJIBOUTI("Djibouti"),
    DOMINICA("Dominica"),
    EGITO("Egito"),
    EL_SALVADOR("El Salvador"),
    EMIRADOS_ARABES_UNIDOS("Emirados Árabes Unidos"),
    EQUADOR("Equador"),
    ERITREIA("Eritreia"),
    ESLOVAQUIA("Eslováquia"),
    ESLOVENIA("Eslovênia"),
    ESPANHA("Espanha"),
    ESTADOS_UNIDOS("Estados Unidos"),
    ESTONIA("Estônia"),
    ETIOPIA("Etiópia"),
    FIJI("Fiji"),
    FILIPINAS("Filipinas"),
    FINLANDIA("Finlândia"),
    FRANCA("França"),
    GABAO("Gabão"),
    GAMBIA("Gâmbia"),
    GANA("Gana"),
    GEORGIA("Geórgia"),
    GIBRALTAR("Gibraltar"),
    GRANADA("Granada"),
    GRECIA("Grécia"),
    GROENLANDIA("Groenlândia"),
    GUADALUPE("Guadalupe"),
    GUAM("Guam"),
    GUATEMALA("Guatemala"),
    GUERNSEY("Guernsey"),
    GUINE("Guiné"),
    GUINE_BISSAU("Guiné-Bissau"),
    GUINE_EQUATORIAL("Guiné Equatorial"),
    GUIANA("Guiana"),
    GUIANA_FRANCESA("Guiana Francesa"),
    HAITI("Haiti"),
    HONDURAS("Honduras"),
    HONG_KONG("Hong Kong"),
    HUNGRIA("Hungria"),
    IEMEN("Iêmen"),
    ILHAS_CAYMAN("Ilhas Cayman"),
    ILHAS_COOK("Ilhas Cook"),
    ILHAS_FALKLAND("Ilhas Falkland"),
    ILHAS_MARSHALL("Ilhas Marshall"),
    ILHAS_SALOMAO("Ilhas Salomão"),
    ILHAS_TURCAS_E_CAICOS("Ilhas Turcas e Caicos"),
    ILHAS_VIRGENS_AMERICANAS("Ilhas Virgens Americanas"),
    ILHAS_VIRGENS_BRITANICAS("Ilhas Virgens Britânicas"),
    INDIA("Índia"),
    INDONESIA("Indonésia"),
    IRA("Irã"),
    IRAQUE("Iraque"),
    IRLANDA("Irlanda"),
    ISLANDIA("Islândia"),
    ISRAEL("Israel"),
    ITALIA("Itália"),
    JAMAICA("Jamaica"),
    JAPAO("Japão"),
    JERSEY("Jersey"),
    JORDANIA("Jordânia"),
    KAZAQUISTAO("Cazaquistão"),
    KIRIBATI("Kiribati"),
    KUWAIT("Kuwait"),
    LAOS("Laos"),
    LESOTO("Lesoto"),
    LETONIA("Letônia"),
    LIBANO("Líbano"),
    LIBERIA("Libéria"),
    LIBIA("Líbia"),
    LIECHTENSTEIN("Liechtenstein"),
    LITUANIA("Lituânia"),
    LUXEMBURGO("Luxemburgo"),
    MACAU("Macau"),
    MADAGASCAR("Madagascar"),
    MALASIA("Malásia"),
    MALAUI("Malawi"),
    MALDIVAS("Maldivas"),
    MALI("Mali"),
    MALTA("Malta"),
    MARROCOS("Marrocos"),
    MARTINICA("Martinica"),
    MAURICIO("Maurício"),
    MAURITANIA("Mauritânia"),
    MEXICO("México"),
    MICRONESIA("Micronésia"),
    MOCAMBIQUE("Moçambique"),
    MOLDOVA("Moldávia"),
    MONACO("Mônaco"),
    MONGOLIA("Mongólia"),
    MONTENEGRO("Montenegro"),
    MONTSERRAT("Montserrat"),
    NAMIBIA("Namíbia"),
    NAURU("Nauru"),
    NEPAL("Nepal"),
    NICARAGUA("Nicarágua"),
    NIGER("Níger"),
    NIGERIA("Nigéria"),
    NIUE("Niue"),
    NORUEGA("Noruega"),
    NOVA_CALEDONIA("Nova Caledônia"),
    NOVA_ZELANDIA("Nova Zelândia"),
    OMA("Omã"),
    PAISES_BAIXOS("Países Baixos"),
    PALAU("Palau"),
    PALESTINA("Palestina"),
    PANAMA("Panamá"),
    PAPUA_NOVA_GUINE("Papua-Nova Guiné"),
    PAQUISTAO("Paquistão"),
    PARAGUAI("Paraguai"),
    PERU("Peru"),
    POLINESIA_FRANCESA("Polinésia Francesa"),
    POLONIA("Polônia"),
    PORTUGAL("Portugal"),
    PORTO_RICO("Porto Rico"),
    QATAR("Catar"),
    QUENIA("Quênia"),
    QUIRGUISTAO("Quirguistão"),
    REUNIAO("Reunião"),
    ROMENIA("Romênia"),
    RUANDA("Ruanda"),
    RUSSIA("Rússia"),
    SALVADOR("El Salvador"),
    SAMOA("Samoa"),
    SAN_MARINO("San Marino"),
    SANTA_HELENA("Santa Helena"),
    SANTA_LUCIA("Santa Lúcia"),
    SAO_BARTOLOMEU("São Bartolomeu"),
    SAO_CRISTOVAO_E_NEVIS("São Cristóvão e Nevis"),
    SAO_TOME_E_PRINCIPE("São Tomé e Príncipe"),
    SAO_VICENTE_E_GRANADINAS("São Vicente e Granadinas"),
    SENEGAL("Senegal"),
    SERVIA("Sérvia"),
    SEYCHELLES("Seychelles"),
    SERRA_LEOA("Serra Leoa"),
    SINGAPURA("Singapura"),
    SIRIA("Síria"),
    SOMALIA("Somália"),
    SRI_LANKA("Sri Lanka"),
    SUAZILANDIA("Suazilândia"),
    SUDAO("Sudão"),
    SUDAO_DO_SUL("Sudão do Sul"),
    SUECIA("Suécia"),
    SUICA("Suíça"),
    SURINAME("Suriname"),
    TAILANDIA("Tailândia"),
    TAIWAN("Taiwan"),
    TADJIQUISTAO("Tajiquistão"),
    TANZANIA("Tanzânia"),
    TIMOR_LESTE("Timor-Leste"),
    TOGO("Togo"),
    TONGA("Tonga"),
    TRINIDAD_E_TOBAGO("Trinidad e Tobago"),
    TUNISIA("Tunísia"),
    TURCOMENISTAO("Turcomenistão"),
    TURQUIA("Turquia"),
    TUVALU("Tuvalu"),
    UCRANIA("Ucrânia"),
    UGANDA("Uganda"),
    URUGUAI("Uruguai"),
    UZBEQUISTAO("Uzbequistão"),
    VANUATU("Vanuatu"),
    VATICANO("Vaticano"),
    VENEZUELA("Venezuela"),
    VIETNA("Vietnã"),
    ZAMBIA("Zâmbia"),
    ZIMBABUE("Zimbábue");

    private final String descricao;

    Pais(String descricao) {
        this.descricao = descricao;
    }

    @JsonValue
    public String getDescricao() {
        return descricao;
    }

    @JsonCreator
    public static Pais fromString(String value) {
        for (Pais p : Pais.values()) {
            if (p.descricao.equalsIgnoreCase(value)) {
                return p;
            }
        }
        throw new IllegalArgumentException("Valor inválido para Componente: " + value);
    }
}
